// examples/react/App.tsx
import React, { useEffect, useRef } from 'react';
import '@agent-ui/chat-sdk';
import type { AgentChatConfig, AgentChatWidget } from '@agent-ui/chat-sdk';

// Extend JSX intrinsic elements to include the custom elements
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'agent-chat-widget': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement>, HTMLElement>;
      'agent-chat-panel': React.DetailedHTMLProps<
        React.HTMLAttributes<HTMLElement> & { mode?: string },
        HTMLElement
      >;
    }
  }
}

const CHAT_CONFIG: AgentChatConfig = {
  endpoint: 'https://your-backend.example.com/api/chat/stream',
  theme: {
    colorPrimary: '#7c3aed',
    borderRadius: '0.85rem',
  },
  labels: {
    title: 'AI Assistant (React)',
    placeholder: 'Ask me anything…',
    emptyState: 'Hi from React! How can I help?',
  },
  initialMessages: [
    { role: 'assistant', content: 'Hello from React! How can I help you today?' },
  ],
  actions: [
    { id: 'start', label: '🚀 Get started', message: 'How do I get started?' },
  ],
};

export default function App() {
  const widgetRef = useRef<AgentChatWidget>(null);

  // Set config on mount (imperative API for custom elements in React)
  useEffect(() => {
    if (widgetRef.current) {
      widgetRef.current.config = CHAT_CONFIG;
    }
  }, []);

  // Listen for SDK events
  useEffect(() => {
    const handleSent = (e: Event) => {
      console.log('[React] Message sent:', (e as CustomEvent).detail);
    };
    const handleReceived = (e: Event) => {
      console.log('[React] Message received:', (e as CustomEvent).detail);
    };
    const handleError = (e: Event) => {
      console.error('[React] Chat error:', (e as CustomEvent).detail);
    };

    document.addEventListener('agent-chat:message-sent', handleSent);
    document.addEventListener('agent-chat:message-received', handleReceived);
    document.addEventListener('agent-chat:error', handleError);

    return () => {
      document.removeEventListener('agent-chat:message-sent', handleSent);
      document.removeEventListener('agent-chat:message-received', handleReceived);
      document.removeEventListener('agent-chat:error', handleError);
    };
  }, []);

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', padding: '2rem' }}>
      <h1 style={{ fontSize: '1.5rem', marginBottom: '0.5rem' }}>
        Agent Chat SDK — React Example
      </h1>
      <p style={{ color: '#64748b', marginBottom: '2rem' }}>
        The floating chat widget is in the bottom-right corner.
        The panel below is embedded inline.
      </p>

      {/* Inline panel — config set via ref in useEffect */}
      <div style={{ height: 500, borderRadius: '1rem', overflow: 'hidden', border: '1px solid #e2e8f0' }}>
        <agent-chat-panel
          mode="panel"
          ref={(el: HTMLElement | null) => {
            if (el) {
              // Cast to access the config setter
              const panel = el as HTMLElement & { config: AgentChatConfig };
              panel.config = { ...CHAT_CONFIG, mode: 'panel' };
            }
          }}
          style={{ display: 'block', height: '100%' }}
        />
      </div>

      {/* Floating widget */}
      {/* @ts-expect-error — ref typed via AgentChatWidget */}
      <agent-chat-widget ref={widgetRef} />
    </div>
  );
}

// examples/vue/App.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import '@agent-ui/chat-sdk';
import type { AgentChatConfig, AgentChatWidget } from '@agent-ui/chat-sdk';

const widgetRef = ref<AgentChatWidget | null>(null);
const panelRef = ref<HTMLElement | null>(null);

const config: AgentChatConfig = {
  endpoint: 'https://your-backend.example.com/api/chat/stream',
  theme: {
    colorPrimary: '#059669',
    borderRadius: '0.85rem',
  },
  labels: {
    title: 'AI Assistant (Vue)',
    placeholder: 'Type a message…',
    emptyState: 'Hi from Vue! How can I help?',
  },
  initialMessages: [
    { role: 'assistant', content: 'Hello from Vue 3! How can I help you today?' },
  ],
  actions: [
    { id: 'help', label: '💬 Ask anything', message: 'What can you help me with?' },
  ],
};

onMounted(() => {
  // Set config via imperative property (custom elements don't accept complex objects as attributes)
  if (widgetRef.value) {
    widgetRef.value.config = config;
  }
  if (panelRef.value) {
    (panelRef.value as HTMLElement & { config: AgentChatConfig }).config = {
      ...config,
      mode: 'panel',
    };
  }

  // Listen for SDK events
  document.addEventListener('agent-chat:message-sent', (e: Event) => {
    console.log('[Vue] Sent:', (e as CustomEvent).detail);
  });
});
</script>

<template>
  <div class="app">
    <header>
      <h1>Agent Chat SDK — Vue 3 Example</h1>
    </header>

    <main>
      <div class="panel-container" ref="panelRef">
        <!-- Config set imperatively in onMounted -->
        <agent-chat-panel mode="panel" ref="panelRef" />
      </div>
    </main>

    <!-- Floating widget (config set imperatively in onMounted) -->
    <agent-chat-widget ref="widgetRef" />
  </div>
</template>

<style scoped>
.app {
  font-family: system-ui, sans-serif;
  min-height: 100vh;
  background: #f8fafc;
}

header {
  background: #1e293b;
  color: #fff;
  padding: 1rem 2rem;
}

header h1 {
  font-size: 1.2rem;
  font-weight: 600;
}

main {
  padding: 2rem;
  max-width: 800px;
  margin: 0 auto;
}

.panel-container {
  height: 500px;
  border-radius: 1rem;
  overflow: hidden;
  border: 1px solid #e2e8f0;
  background: #fff;
}

agent-chat-panel {
  display: block;
  height: 100%;
}
</style>
